# -*- coding: utf-8 -*-
"""GovernmentAPI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/178D4zN_rhR316S7LCNKr1kob93DZe6KZ
"""

#https://govspending.data.go.th/api/documentation
import requests
from pprint import pprint #เวลา print จะแสดงเป็นบรรทัดเรียงลงไป ซึ่งปกติจะยาวบรรทัดเดียว ดูยาก


def SearchProject(keyword_search='พระมหากษัตริย์',year=2564,limit=50):

    url = 'https://opend.data.go.th/govspending/cgdcontract'
    token = '7EMfzuuQZXcCWhoE7ksjRYbfzsYpKcqR'
    parameters = {'api-key':token,
                'year':year,
                'keyword':keyword_search,
                'limit':limit #จำนวนที่ให้แสดงผล
                }

        
    r = requests.get(url,params=parameters)
    result = r.json()
    allproject = result['result']
    print('Count: ',len(allproject)) #len() คือการนับค่าใน list / Dict
    #pprint(allproject) #เรียกดู project ทั้งหมด
    #pprint(allproject[3]) #เลือกดูเฉพาะ project ที่ 4

    allbudget = [] #เอาไว้เก็บค่า sum_price_agree เพื่อ sum เงินทั้งหมด

    print('----------parameter----------')
    print(allproject[0].keys()) #ดูว่ามีหัวข้ออะไรให้เลือกดูข้อมูลบ้าง เลือกไปใส่เป็น i in allproject

    #เลือกดูรายการเฉพาะที่สนใจในแต่ละ project
    for i in allproject:
        print(i['dept_name'])
        print(i['project_name'])
        print(i['purchase_method_name'])
        print(i['sum_price_agree'])
        allbudget.append(int(i['sum_price_agree'].replace(',','')))
        print('..........................')
    print('******************************************************************')
    print('ค้นหาคำว่า: {} งบประมาณทั้งหมด: {:,d} บาท'.format(keyword_search,sum(allbudget))) #,d คือการใส่คอมม่าในตัวเลขเงิน
    print('******************************************************************')

SearchProject('vaccine')

